vich_uploader:
    db_driver: orm

    mappings:
        profile_resume:
            uri_prefix: '%app.path.profile_resume%'
            upload_destination: '%kernel.project_dir%/public%app.path.profile_resume%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        profile_picture:
            uri_prefix: '%app.path.profile_picture%'
            upload_destination: '%kernel.project_dir%/public%app.path.profile_picture%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        profile_passport:
            uri_prefix: '%app.path.profile_passport%'
            upload_destination: '%kernel.project_dir%/public%app.path.profile_passport%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
