vich_uploader:
    db_driver: orm

    mappings:
        profile_resume:
            uri_prefix: '%app.path.profile_resume%'
            upload_destination: '%kernel.project_dir%/public/assets%app.path.profile_resume%'
        profile_image:
            uri_prefix: '%app.path.profile_image%'
            upload_destination: '%kernel.project_dir%/public/assets%app.path.profile_image%'
        profile_passport:
            uri_prefix: '%app.path.profile_passport%'
            upload_destination: '%kernel.project_dir%/public/assets%app.path.profile_passport%'
